apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abs-iip-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: abs-iip.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: abs-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: abs-frontend
                port:
                  number: 8501
