from __future__ import annotations

import os
import uuid
from datetime import datetime
from pathlib import Path

import qrcode
from fpdf import FPDF
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.branding import Branding
from app.models.enums import ReportType
from app.models.joint import Joint
from app.models.project import Project
from app.models.report import Report
from app.models.tenant import Tenant
from app.models.work_order import WorkOrder


class ReportPDF(FPDF):
    pass


def _safe_image(pdf: FPDF, path: str | None, x: float, y: float, w: float) -> None:
    if not path:
        return
    if not os.path.exists(path):
        return
    try:
        pdf.image(path, x=x, y=y, w=w)
    except Exception:
        return


def _load_branding(db: Session, tenant_id: str) -> tuple[str | None, str, str, str]:
    tenant = db.get(Tenant, tenant_id)
    branding = db.query(Branding).filter(Branding.tenant_id == tenant_id).first()

    client_logo = branding.company_logo_path if branding else None
    client_name = branding.client_display_name if branding else (tenant.name if tenant else "Client")
    primary = branding.primary_color if branding else "#0f4c81"
    secondary = branding.secondary_color if branding else "#1f2937"

    return client_logo, client_name, primary, secondary


def _status_summary_for_joint(db: Session, joint: Joint) -> dict[str, int]:
    from app.models.bolt import Bolt
    from app.models.enums import BoltResult

    bolts = db.query(Bolt).filter(Bolt.tenant_id == joint.tenant_id, Bolt.joint_id == joint.id).all()
    return {
        "ok": sum(1 for bolt in bolts if bolt.result == BoltResult.OK),
        "nok": sum(1 for bolt in bolts if bolt.result in {BoltResult.NOK, BoltResult.OUT_OF_TOLERANCE}),
        "missing": sum(1 for bolt in bolts if bolt.result == BoltResult.MISSING),
    }


def generate_pdf_report(
    db: Session,
    *,
    tenant_id: str,
    report_type: ReportType,
    generated_by_user_id: str | None,
    base_verify_url: str,
    project_id: str | None = None,
    work_order_id: str | None = None,
    joint_id: str | None = None,
) -> Report:
    settings = get_settings()

    project = db.get(Project, project_id) if project_id else None
    work_order = db.get(WorkOrder, work_order_id) if work_order_id else None
    joint = db.get(Joint, joint_id) if joint_id else None

    token = uuid.uuid4().hex
    tenant_dir = settings.report_dir / tenant_id
    tenant_dir.mkdir(parents=True, exist_ok=True)

    pdf_file = tenant_dir / f"{token}.pdf"
    qr_file = tenant_dir / f"{token}.png"

    verify_url = f"{base_verify_url.rstrip('/')}/api/v1/verify/{token}"
    qrcode.make(verify_url).save(qr_file)

    client_logo, client_name, primary, secondary = _load_branding(db, tenant_id)

    pdf = ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=12)
    pdf.add_page()

    _safe_image(pdf, settings.abs_logo_path, x=10, y=8, w=30)
    _safe_image(pdf, client_logo, x=170, y=8, w=28)

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(10, 20)
    pdf.cell(0, 10, "ABS Industrial Intelligence Platform", ln=1)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 6, f"Report Type: {report_type.value}", ln=1)
    pdf.cell(0, 6, f"Client: {client_name}", ln=1)
    pdf.cell(0, 6, f"Generated At: {datetime.utcnow().isoformat()} UTC", ln=1)

    if project is not None:
        pdf.cell(0, 6, f"Project: {project.name} | Location: {project.location}", ln=1)
    if work_order is not None:
        pdf.cell(0, 6, f"Work Order: {work_order.code} - {work_order.name}", ln=1)
    if joint is not None:
        pdf.cell(0, 6, f"Joint: {joint.joint_id} | Status: {joint.status.value}", ln=1)

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 7, "Engineering Summary", ln=1)
    pdf.set_font("Helvetica", "", 10)

    if joint is not None:
        summary = _status_summary_for_joint(db, joint)
        pdf.cell(0, 6, f"Bolt Count: {joint.bolt_count}", ln=1)
        pdf.cell(0, 6, f"Target Torque: {joint.target_torque} Nm | Tolerance: {joint.torque_tolerance}", ln=1)
        pdf.cell(0, 6, f"OK: {summary['ok']} | NOK: {summary['nok']} | Missing: {summary['missing']}", ln=1)

    pdf.ln(3)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(
        0,
        5,
        "Digital certificate: This report is generated by ABS Industrial Intelligence Platform. "
        "Scan the QR code below to verify authenticity and live joint status.",
    )

    pdf.image(str(qr_file), x=10, y=pdf.get_y() + 2, w=35)
    pdf.set_xy(50, pdf.get_y() + 6)
    pdf.multi_cell(0, 5, f"Verification URL: {verify_url}")

    pdf.output(str(pdf_file))

    report = Report(
        tenant_id=tenant_id,
        report_type=report_type,
        project_id=project_id,
        work_order_id=work_order_id,
        joint_id=joint_id,
        file_path=str(pdf_file),
        qr_token=token,
        generated_by_user_id=generated_by_user_id,
    )
    db.add(report)
    db.flush()

    return report


def verify_report_token(db: Session, token: str) -> dict:
    report = db.query(Report).filter(Report.qr_token == token).first()
    if report is None:
        return {"valid": False}

    tenant = db.get(Tenant, report.tenant_id)
    project = db.get(Project, report.project_id) if report.project_id else None
    joint = db.get(Joint, report.joint_id) if report.joint_id else None

    return {
        "valid": True,
        "tenant_name": tenant.name if tenant else None,
        "report_type": report.report_type.value,
        "joint_id": joint.joint_id if joint else None,
        "project_name": project.name if project else None,
        "generated_at": report.created_at.isoformat() if report.created_at else None,
    }
